### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by meihailang** [SP-FA/DeepPlace#2]
请问您使用的cuda版本是什么，一定要cuda10.2吗，我的机器不支持cuda10.2，跑的时候显示没有内核映像

**Comment by SP-FA** [comment]
我使用的 cuda 11.8

**Comment by meihailang** [comment]
谢谢您的回答！，我还有另一个问题，文件夹data下的文件数据是如何生成的，如n_edges_710.dat?




梅海浪:-*
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SP-FA/DeepPlace"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 凌晨4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SP-FA/DeepPlace] 环境问题 (Issue #2)





 
我使用的 cuda 11.8
