### ISSUE TITLE
第一阶段用强化学习得到的结果，如何应用于第二阶段，我看到第二阶段直接就读取json文件了？

### ISSUE THREAD

**Issue by meihailang** [SP-FA/DeepPlace#3]

**Comment by SP-FA** [comment]
你说的第一第二阶段指什么？

**Comment by meihailang** [comment]
感谢您的回答。就是place后，得到的结果是什么，该怎么用到fullplace里面，我看到fullplace直接加载的json文件。我能与您交换微信嘛，目前研究方向是这方面的，想向您请教学习。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 凌晨1:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SP-FA/DeepPlace] 第一阶段用强化学习得到的结果，如何应用于第二阶段，我看到第二阶段直接就读取json文件了？ (Issue #3)




 
你说的第一第二阶段指什么？

**Comment by SP-FA** [comment]
可以的 yzc2997839760

**Comment by SP-FA** [comment]
在 fullplace 里，第一阶段应该指的是 macro 的放置，放置结果保存到了json文件里，然后第二阶段应该是 cell 的放置，这里直接调用 dreamplace，dreamplace 会读取 json 里的 macro 信息，在此基础上放置 cell
